{% set name = "stac-check" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stac_check-{{ version }}.tar.gz
  sha256: 5bcba6946e02c25ce89f1518701cd4159774b91780109dd37c90b360d3ae7b74

build:
  entry_points:
    - stac-check=stac_check.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1.2
    - jsonschema >=3.1.2b0
    - pystac >=1.1.0
    - pytest
    - python >=3.7
    - python-dotenv
    - pyyaml
    - requests >=2.19.1
    - stac-validator >=3.0.0

test:
  imports:
    - stac_check
  commands:
    - pip check
    - stac-check --help
  requires:
    - pip

about:
  home: https://github.com/stac-utils/stac-check
  summary: Linting and validation tool for STAC assets
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/stac-utils/stac-check
  dev_url: https://github.com/stac-utils/stac-check

extra:
  recipe-maintainers:
    - jonhealy1
